### ISSUE TITLE
Which mime types are supported?

### ISSUE THREAD

**Issue by bobvanluijt** [go-swagger/go-swagger#1022]
I seem to be unable to find supported mime-types that the API's can consume and produce.

Any references?

**Comment by casualjim** [comment]
at this point these are supported in the code generator: https://github.com/go-swagger/go-swagger/blob/master/generator/support.go#L317-L335

We can add more through the consumer producer mechanism if you need more

**Comment by bobvanluijt** [comment]
Wonderful, thanks.

1. Did a minor pull request: https://github.com/go-swagger/go-swagger.github.io/pull/8
2. Protobuf would be very much appreciated 👍 

Cheers

**Comment by archer96** [comment]
The info appears to have been removed? Because I can't find any information about supported producer mime types. 😃 

Imagine having following `swagger.yml`

```yml
...
  /users/{userId}/image:
    get:
      tags:
      - user
      description: Get the user's profile image
      operationId: getUserImage
      parameters:
        - name: userId
          in: path
          description: The ID of the user
          required: true
          type: string
      produces:
        - application/octet-stream
      responses:
        200:
          description: Success
          schema:
            type: string
            format: binary
...
```

The API produces the binary/image with `application/octet-stream` just as intended. But writing e.g. `image/jpeg` in `produces` does not work because no producer is registered for it. It took me quite a while to figure this out because no error message was printed out and I thought that my `io.ReadCloser` simply didn't work.

I am using go-swagger to generate `go` code from my swagger spec. Is there a way to register another producer? Because the `xxx_api.go` is generated, I can't add it manually or can I?

(btw. I'm a `go` novice and just recently started using `go-swagger`)

Maybe an error should be printed if not supported (binary) mime types are used?

### Environment
swagger version: 
-> version: 0.12.0
-> commit: 8135eb6728e43b73489e80f94426e6d387809502
go version: `go version go1.9.2 windows/amd64`
OS:   Windows 10

**Comment by fredbi** [comment]
See also #1284
