### ISSUE TITLE
configureServer has incorrect number of arguments

### ISSUE THREAD

**Issue by frosenberg** [go-swagger/go-swagger#1099]
## Swagger specification
N/A (use any).

```
swagger generate server -f swagger.yml -t api_v1 --model-package=restmodels --server-package=server --exclude-main -A Example
```

## Steps to reproduce
Run any swagger yaml through the latest code and I get the following compile errors in the generated `server.go`.

1. `configureServer(domainSocket, "unix", string(s.SocketPath))` 
1. `configureServer(httpServer, "http", s.httpServerL.Addr().String())`
1. `configureServer(httpsServer, "https", s.httpsServerL.Addr().String())` 

In all cases the last argument needs to be removed to solve the problem.

## Environment
swagger version: `dev` (latest)
go version: 1.8.2
OS: Mac OS 10.12.3

**Comment by casualjim** [comment]
it's the other way around. in your configure_xxx.go file you have to add the argument to the configureServer callback.
This was changed a while ago so you can know which scheme you're configuring for

**Comment by frosenberg** [comment]
Sorry I cannot follow. `swagger generate` generates code for me that does not compile. I don't see how the callback helps me.

**Comment by casualjim** [comment]
there is a file called restapi/configure_xxx.go that is only generated once. it contains callbacks for you to add your own code. https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/restapi/configure_todo_list.go#L70

that signature has changed in the generated code which is why the code doesn't compile, you just have to update that signature in your configure_xxx.go file.
Point is it's not a bug

**Comment by frosenberg** [comment]
Thanks!
