### ISSUE TITLE
[Help Wanted] How to support generate type int(not type int64)? 

### ISSUE THREAD

**Issue by allencloud** [go-swagger/go-swagger#1205]
## Problem statement

Actually I need to use swagger to generate my modes in go code. But I find I can hardly generate type `int`, always `int64`.

Since I need to keep back compatibility the project, I can hardly change the type. So in this case, do go-swagger meet my demand? If the answer is yes, how to make it.

Please remove the sections that don't apply

## Environment
```
~ $ uname -a
Darwin AllenSundeMacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
~ $ swagger version
version: 0.12.0
commit: 8135eb6728e43b73489e80f94426e6d387809502
~ $ go version
go version go1.8.3 darwin/amd64
``` 

Thanks in advance

**Comment by gregmarr** [comment]
Discussed briefly in #675

**Comment by allencloud** [comment]
Yeah, it is brief in #675 . While I think we have not get the solution. So I suggest that it is better for us to keep this issue open, since maybe other users would have the same issue. @gregmarr

**Comment by casualjim** [comment]
IMO int is not a good option to support when it comes to contracts.
Consider the following: you have an arm32 client on which int is int32, however your server is amd64. At this stage it's perfectly valid for the server to return int32 max value + 1, this will cause the client to overflow.
So while go allows int as type I think for API contracts int is too ambiguous as definition leading to subtle but hard to debug failures.
Similarly other languages may choose to default to int32 type instead of int64 type regardless of platform.

**Comment by johnnyli4a4c** [comment]
This is also causing an issue for me. Although I do agree that int and uint are not good for enforcing contracts, it shouldn't be dictated by the framework if the language inherently supports it. If strict typing needs to be enforced, that can be done in the swagger spec file.
