### ISSUE TITLE
How to get http.ResponseWriter in the generated code

### ISSUE THREAD

**Issue by huikang** [go-swagger/go-swagger#1229]
In some of my API implementation, both the ResponseWriter and http.Request are needed.
I know that I can get the (r *http.Request) by 

```go
_, err := myFunc(params.HTTPRequest)
```

However, I could not find where to get the instance of  http.ResponseWriter in the generated code. Can anyone help? Thanks.

**Comment by casualjim** [comment]
Implement a responder, by default we generate a few we can infer from the swagger spec but you can easily implement your own.

it's essentially  a `func(http.ResponseWriter, runtime.Producer)`

https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L56-L68

**Comment by huikang** [comment]
Thanks @casualjim

**Comment by sachnk** [comment]
Hi @casualjim 

I think this is problematic if you're using something like [Gorilla Sessions](http://www.gorillatoolkit.org/pkg/sessions), where you need to invoke a `session.save(rw, r)`, where `rw` is an `http.ResponseWriter` and `r` is an `http.Request`, *before* you return your responder.

In my case, I call `session.save(rw, r)` to get the session ID and then I need to save that value to the database. I don't see how I can do that with responder implementation, since the responder is invoked only after the route returns...

**Comment by casualjim** [comment]
the responder executes  in the context of a web request. You can do it in a responder because it's essentially a call back. Afaict gorilla sessions wants you to call it before exiting `ServeHTTP` which it will.

```go
api.StaticSayHelloHandler = static.SayHelloHandlerFunc(func(params static.SayHelloParams) middleware.Responder {

  originalResponder := getSomeResponder()

  return middleware.ResponderFunc(func(rw http.ResponseWriter, p runtime.Producer){
    
    session.save(rw, params.HTTPRequest)
    originalResponder.WriteResponse(rw, p)
  })
})
```

**Comment by sachnk** [comment]
Hmm, I see, thanks. That seems to work.

I also tried modifying the template to include the `http.ResponseWriter` within the input parameter object of every request, just like how `http.Request` is stored.

This strikes me as having more symmetrical semantics and usage. Unless there's some obvious downside I'm unaware of...
