### ISSUE TITLE
Properties in "AllOf1" structs don't get marshaled in generated client

### ISSUE THREAD

**Issue by ahilananantha** [go-swagger/go-swagger#1232]
## Problem statement

When not specifying --skip-flatten, client codegen fails to marshal the AllOf1 structs. You'll get code like this:

```go
        b1, err = json.Marshal(struct {
                CatAllOf1 /*trouble*/

        }{},
        )
```

while I think instead this would work:

```go
        b1, err = json.Marshal(m.CatAllOf1)
```

the unmarshal also claims "trouble":

```go
        var data struct {
                CatAllOf1 /*trouble*/

        }
```

although it might still work?

## Swagger specification

I think this one copied from ./fixtures/bugs/540/swagger.yml will show the issue:

```yaml
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
    - petType

  Cat:
    type: object
    description: A representation of a cat
    allOf:
    - $ref: '#/definitions/Pet'
    - properties:
        huntingSkill:
          type: string
          description: The measured skill for hunting
          default: lazy
          enum:
          - clueless
          - lazy
          - adventurous
          - aggressive
      required:
      - huntingSkill
```

## Environment
swagger version: dev
go version: 1.9.0  
OS:   darwin/amd64

**Comment by fredbi** [comment]
There might be a problem on the generated client, that I haven't test, but I can assert that the model marshals,  unmarshals and validates okay with current master (flatten or not flatten).

I assume this is more a misunderstanding about how to marshal polymorphic types: you don't use json.Marshall, but instead, use the interface and use the UnmarshalPet() method. This one knows how to discriminate and there is no "trouble".

This is how the server works.  As far as I could see, the client is doing the same.

@ahilananantha can you confirm this may be reasonably closed now?
I let the issue open for client, since I did not confirm the behavior with client.

**Comment by RubenGarcia** [comment]
I'm also affected.

**Comment by ahilananantha** [comment]
I know this is quite a bit late to report, but the latest versions have been working fine for me.
