### ISSUE TITLE
Why is everything a pointer?

### ISSUE THREAD

**Issue by macrael** [go-swagger/go-swagger#1386]
I don't know if there is a mailing list where it would be better to ask this question, but I'm curious why all the requests and responses that are generated are filled out with pointers rather than raw types.

**Comment by gregmarr** [comment]
Anything required is almost always a pointer, so that the validator can tell whether it was provided or not.  Generally structs are also by pointer instead of by value.  You can sometimes use `x-nullable: false` to change that.

**Comment by shyr** [comment]
IMHO, without pointer we cannot tell some value is provided value or not(zero value).

**Comment by gregmarr** [comment]
To clarify, the requirement that something be a pointer to tell if it was provided or not is because  the validation is done on the resulting objects themselves after the data is extracted from the JSON rather than as the data is being extracted from the JSON.  As such, it doesn't have a way to tell if the data was provided in the JSON.  This also allows the same validation code to be used both for extracting objects from JSON and for creating JSON from objects.  It could theoretically be written such that the validation was done during the marshal/unmarshal, but that seems like it would be a significant rewrite of the entire process.

**Comment by macrael** [comment]
Thanks all! Is there a mailing list for this project or are GitHub issues the best forum for questions?

**Comment by gregmarr** [comment]
There is a slack workspace: https://goswagger.slack.com

**Comment by macrael** [comment]
How do I request access to it?

**Comment by gregmarr** [comment]
I don't remember. @casualjim ?

**Comment by macrael** [comment]
I found it! https://slackin.goswagger.io

**Comment by drewwells** [comment]
Still a relevant question, what is the ultimate answer? The swagger channel on Golang's swagger seems to be inactive, and the go-swagger account doesn't have any history.

I'm disappointed that all generated struct properties use pointers, since it's impossible to write a struct literal with pointer strings. One of the nice things about Go is that every type has a relevant zero value. A useful blog post talking about this subject: https://dave.cheney.net/2013/01/19/what-is-the-zero-value-and-why-is-it-useful

**Comment by macrael** [comment]
I think that building an API that is incapable of differentiating between someone omitting an int field and someone setting it to zero is a pretty serious limitation for API design. Now, it's possible that you could redesign this so that all the API validation happened in another layer and then for required fields the structs that go-swagger fills out could use non-pointer types but that would be a pretty significant change. 

I've written little functions like stringPointer() and intPointer() so that I can construct struct literals with pointers.

**Comment by casualjim** [comment]
@drewwells you can use `x-isnullable: false` on those properties where you don't care about the distinction between null and the zero value.
it's not like the zero values are an unknown thing to us, it's just that that particular trade-off works in a go app where you're behind your fence. However an API boundary is your fence and there you need that to go from a type system that's language agnostic to go's type system

We provide these helpers to make dealing with that distinction easier https://github.com/go-openapi/swag/blob/master/convert_types.go
