### ISSUE TITLE
Add new param type: json

### ISSUE THREAD

**Issue by schickling** [go-swagger/go-swagger#140]
It would be nice to have an additional param type like `json` which just takes a go struct and uses it as a default JSON `body`.

Here is an example:

```go
type LoginPayload struct {
	Email    string `json:"email"`
	UserName string `json:"user_name"`
	// Required: true
	Password string `json:"password"`
}

// swagger:parameters login
type ImplicitWrapperStruct struct {
	// In: body
	Body PersonLoginPayload
}
```

**Comment by casualjim** [comment]
it already works this way.
There is no param type json but the anntotations you provide should in fact work in that way.

**Comment by schickling** [comment]
Hi @casualjim. Maybe I didn't make it clear enough. I was hoping for a way **without** the wrapper struct.

**Comment by casualjim** [comment]
At this moment I'm inclinded to say that this is an optimization with pretty low ROI. But I'll leave the ticket open, and if more people want it they should put their +1 here.

**Comment by schickling** [comment]
Thanks!

**Comment by jonathaningram** [comment]
@casualjim I just came across this and for me this wouldn't be about optimising, but more about having to change your Go code so that it works with the swagger generator, opposed to swagger just working with your code, right? I mean, would you find a blog article on writing a standard Go handler func that says "make sure that you use a wrapper struct so that swagger generate can handle it"? Not sure if that makes sense...?

cc @schickling

**Comment by casualjim** [comment]
It was never spelled out in this thread why it is the way it is, so here it goes:

The reason a body struct is wrapped atm is because for swagger a response is headers + body, and so my scanner wants to preserve that behavior.

I wouldn't refuse a PR that addresses this through a `swagger:bodyResponse` annotation instead of `swagger:model` or `swagger:response`

**Comment by jjeffrey-bolste** [comment]
@casualjim  My pr did not address what they were talking about as he Is talking about paramaters not response. I do plan on doing a pr to add `swagger:bodyparamaters` though
