### ISSUE TITLE
Do we have to specifically allow HEAD requests?

### ISSUE THREAD

**Issue by pschuegr** [go-swagger/go-swagger#1426]
## Problem statement

I was surprised to see that with two routes that supported GET method (below) that one of them allowed me to curl the endpoint (the first) normally, while the other required me to specify `-X GET` in my curl request.  The `/healthcheck` endpoint below returns a 405 Method not allowed for the HEAD request when curling without `-X GET`, where the `/swagger.json` returns a 200.  This feels a bit odd.  Any thoughts?

## Swagger specification

```
  /swagger.json:
    get:
      operationId: getSwaggerDefinition
      responses:
        200:
          description: get swagger definition
          schema:
            type: object
  /healthcheck:
    get:
      operationId: healthCheck
      responses:
        200:
          description: healthy
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
```

## Environment
swagger version: dev  
go version: go1.9 darwin/amd64
OS: osx 10.12.6

**Comment by casualjim** [comment]
swagger.json is handled differently from /healthcheck. We have a middleware that doesn't discriminate for the method of the request for /swagger.json

However for /healthcheck it does exactly what the spec says it should be doing.
So we don't automatically serve head for get requests because there is no rule that says that is implied usage. You would handle it in a different way because you would return a different result for both invocations.

**Comment by pschuegr** [comment]
I see, thanks.  What determines whether the middleware is applied to the request?

**Comment by casualjim** [comment]
the middleware is only present for the swagger.json no other one does it.
You could write a middleware that rewrites HEAD to GET but with a discard stream writer

**Comment by pschuegr** [comment]
Ok, thanks for the information.
