### ISSUE TITLE
Using middle-ware of choice in go-swagger code generation

### ISSUE THREAD

**Issue by sonasingh46** [go-swagger/go-swagger#1468]
## Problem statement
How to use our own middle-ware in go-swagger code generation?
For example, if I want to use gorilla/mux in place of naiona/denco.
I can't find a proper documentation regarding this.

## Environment
swagger version: 2.0.0  
go version: 1.9.2  
OS:Ubuntu 16.04.3 LTS

**Comment by fredbi** [comment]
denco is embedded in go-openapi/runtime

If you want to change that, you need to customize this package

**Comment by casualjim** [comment]
that's not entirely true. the denco based router is a reference implementation.
you need to implement this interface for another router: https://github.com/go-openapi/runtime/blob/master/middleware/router.go#L102-L106

You can then pass it into the context: https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L190-L209

From then on the rest of the generated code will work the same but you'll be using your own router implementation instead of denco

**Comment by sonasingh46** [comment]
Thanks.
