### ISSUE TITLE
Schema rejects default without required properties

### ISSUE THREAD

**Issue by zuxy** [go-swagger/go-swagger#1501]
## Problem statement

go-swagger rejects default object that misses required properties. My understanding is that properties in default and those listed as required are mutually exclusive, because one is supposed to explicitly provide required properties, while properties in default can be filled in. See https://swagger.io/blog/unlocking-the-spec-the-default-keyword

## Swagger specification

```
paths:
  /person/{id}:
    put:
      summary: Put a person
      description: Put a person.
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of person
          required: true
          type: integer
        - in: body
          name: body
          description: Person
          schema:
            type: object
            required:
              - username
            default:
              firstName: John
              lastName: Smith
            properties:
              firstName:
                type: string
              lastName:
                type: string
              username:
                type: string
      responses:
        200:
          description: successful
```

## Steps to reproduce

swagger generate model -f person.yaml

## Environment
swagger version: 21f7c2d92a8a1d1ca15692d22a1ed38ed85bcc9a
go version: 1.10.1
OS:  CentOS 7

**Comment by fredbi** [comment]
@zuxy  your understanding is correct.
The spec validation should warn you about mixing up default with required.

If you override this validation (with `swagger generate model --skip-validation), the model generator would override the required clause, and use the default.

I am not a big fan of this swagger spec restriction, because it is a deviation from the jsonschema spec...

**Comment by fredbi** [comment]
`--skip-validation` skips the call to "swagger validate {spec}` that is normally carried on before generation. 
For some use cases, we have to, since go-swagger supports things that are not stricly swagger-compliant.
This one is an example: some overrides silently take place here.

It is the same if you want, say, to use additionalItems: we support it, but it is not swagger compliant.
