### ISSUE TITLE
How to add static sections?

### ISSUE THREAD

**Issue by larrycinnabar** [go-swagger/go-swagger#1509]
## How to add static sections of docs?

For example I have documentation for supported time formats: lots of time formats, aliases, etc. This is a big piece of documentation and I do not want it to be inserted in every parameter that supports it.

Instead I'd like to put there just a link `(supported formats)` and this link will lead to the static documentation page.

I couldn't find a way of doing this. We only have `swagger:operation` or `swagger:route`. To add endpoint-based items in the menu of documentation. 

Is it possible to add a static, informational page to the menu and link to it from inside comments of docs?

**Comment by casualjim** [comment]
which menu are referring to? the one from redoc?
In any case if you just want to link to a page from a parameter description that should be possible because each description field allows for markdown so you can use [Date Formats](/dateformats.html).
Other than that it depends a bit on how the UI you're using adds things to the menu

**Comment by larrycinnabar** [comment]
I solved the problem with just adding 2-level headers via `##`, that's automatically creates sections in the redoc left menu, ty
