### ISSUE TITLE
Authentication handler is not given request context.

### ISSUE THREAD

**Issue by bweston92** [go-swagger/go-swagger#1668]
## Problem statement

There is no request context on the generated auth handler, for example using the Swagger spec below you get the following auth handler spec.

```
	// APIKeyAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	APIKeyAuthAuth func(string) (interface{}, error)

```

However I would prefer getting the request context passed to me. This mean when I am tracing, my request spans can include the authenticating part too.

## Swagger specification

```
---
  swagger: "2.0"
  securityDefinitions:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  paths:
    /example:
      post:
        security:
          - ApiKeyAuth: []
        responses:
          '200':
            description: OK
```

**Comment by casualjim** [comment]
take a look at how they are implemented, https://github.com/go-openapi/runtime/blob/master/security/authenticator.go#L32

the most convenient authenticators are indeed fairly limited in scope, but you can make your own that have much more context, or use the `context.Context` variants

**Comment by bweston92** [comment]
Sorry how do I "make my own", the API struct generated defines it?

**Comment by casualjim** [comment]
https://github.com/go-swagger/go-swagger/blob/master/examples/authentication/restapi/operations/auth_sample_api.go#L39-L41

**Comment by fredbi** [comment]
See also #1472 .

**Comment by sachnk** [comment]
I'm struggling with this too. How do I change the generated auth function signatures so that it forwards the request context?

> https://github.com/go-swagger/go-swagger/blob/master/examples/authentication/restapi/operations/auth_sample_api.go#L39-L41

The above snippet is modifying a generated file, which is probably not what we want to be doing. Any further guidance / clarification would be immensely helpful!

**Comment by casualjim** [comment]
use this: https://github.com/go-swagger/go-swagger/blob/master/vendor/github.com/go-openapi/runtime/security/authenticator.go#L189

**Comment by sachnk** [comment]
Thanks @casualjim for the prompt reply.

I see the "context" aware authenticators in that file. 

My issue is: how do I actually use them? i.e. how do I configure swagger to generate code that uses `BearerAuthCtx` instead of `BearerAuth`?

I obviously don't want to modify the generated code itself... so is there some other configuration option I can set?

**Comment by casualjim** [comment]
Those are exported properties on the API, so you can just set them in the configure_xxx.go file

**Comment by casualjim** [comment]
oic, we have to add the ctx versions there, you have no way of actually configuring them at this moment

**Comment by sachnk** [comment]
I was able to get things working. For those who might struggle with this, here's what I did. Note, if there's an easier way to achieve this -- I'm all ears :)

1. Added this function to globally do all my APIKey authentication. I use `name` to multiplex which key I need to do authentication on. Thus, I no longer use the `Auth* func(string)` callbacks generated for me per key; I instead put everything into this one callback.

```golang
func Authenticator(name, in string, t security.TokenAuthentication) runtime.Authenticator {
	return security.HttpAuthenticator(func(r *http.Request) (bool, interface{}, error) {
		wrapped := security.APIKeyAuth(name, in, func(token string) (interface{}, error) {
			// do magic auth stuff here
			return "success", nil
		})
		return wrapped.Authenticate(r)
	})
}
```

2. For those of you who might be using the `stratoscale` template (like I am), your life is more difficult because the generated code does not actually expose the `restapi/operations/*api.go`, so you can't assign the `APIKeyAuthenticator` to another value. 

To get around this, I modified the template to accept an `APIKeyAuthenticator` as an input parameter:

In `server/configureapi.gotmpl`:
```golang
// Config is configuration for Handler
type Config struct {
...
  // Authenticator to use for all APIKey authentication
  APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
}
```  
And now assign it after the api instance is created:

```golang
func Handler(c Config) (http.Handler, error) {
...
  api := {{.Package}}.New{{ pascalize .Name }}API(spec)
  api.ServeError = errors.ServeError
  api.Logger = c.Logger

  if c.APIKeyAuthenticator != nil {
    api.APIKeyAuthenticator = c.APIKeyAuthenticator
  }
...
```

**Comment by kylej-ibm** [comment]
I'd like to use the ```BearerAuthCtx(name string, authenticate ScopedTokenAuthenticationCtx) runtime.Authenticator ``` when my swagger server is generated instead of the normal ```BearerAuth```

Has any work been done on this or instructions.  This was mentioned by @casualjim but I haven't seen any updates in documentation on this...

**Comment by casualjim** [comment]
No work has been done to further that integration unfortunately. However the workaround described by @sachnk I think is maybe better because it gives you access to the full request
