### ISSUE TITLE
Move to go modules ?

### ISSUE THREAD

**Issue by MStoykov** [go-swagger/go-swagger#1677]
Given that currently the project looks dep the transitions is probably gonna be smooth and technically both can be used. 

Also I propose:
1. That all openapi libraries also use go modules.
2. Everything is tagged as v1.0.0 and then up the first number whenever something is broken.
3. I do some of the work If there are no objections :)

**Comment by casualjim** [comment]
I'm all for it. We do use the GOPATH env var in a few places.

**Comment by fredbi** [comment]
Just a silly question here: could you tell why this seemingly minor change would deserve the jump to v1.0.0?

**Comment by MStoykov** [comment]
The jump to v1.0.0 would probably be more useful in the openapi's libraries than go-swagger. 
And will at this point mean that you can break backward's comparability and just tag them with v2.0.0 and at least code that uses go modules will still work.
 
Hopefully in the future go-swagger can generate go.mod for all the generated code pointing to versions of the libraries that it(go-swagger) was build with. At which point I for example won't need to figure out myself what versions of the libraries should I put in go.mod when I upgrade the go-swagger I use. 

Also [version numbers are meaningless](https://betanews.com/2018/04/16/linux-kernel-5-0/), unless your tools can make something out of them :)

**Comment by fredbi** [comment]
all go-openapi packages are tagged in line with go-swagger, and dep can currently make something out of this, including breaks in backward compat.

I am not familiar with the go.mod feature, but I don't quite understand why this should come with a change in the current number scheme.

**Comment by MStoykov** [comment]
I would argue listening/watching this [talk](https://www.youtube.com/watch?v=F8nrpe0XWRg) by Russ Cox  on what is now called go modules(before that vgo) is good idea for any go developer and hopefully will explain why I would like to get swagger and all go-opeanpi both it and move them out of the 0.x versions.

**Comment by surajbarkale** [comment]
Can we at least get `v` added to the front of the tag? So tag `0.16.0` should be changed to `v0.16.0`. It is OK if only the newer tags follow this format.

**Comment by casualjim** [comment]
we can add the v prefx in the next release.

I've looked into what would be required to move to go modules.  This is not a trivial change. Everything 
about this leaves a bad taste.

I watched the talk,, the argumentation is reasonable except for go was supposed to be the language where I could write code and not have to update it all the time because of language changes. This is much worse than a language api change, it's a major refactoring of the entire package structure.

This is going to be a lot of work and the incentive is low because there are other solutions out there that are vastly easier to adopt, well-understood trade-offs and workarounds. So I imagine there are more people with similar reservations as I have.

For a complete migration we need to do the following things. Some things are mechanical others will require actual code changes. I'll detail in another issue.

Are there larger projects/packages out there that have already migrated?

**Comment by casualjim** [comment]
You can find more info in #1724

**Comment by casualjim** [comment]
A lot of my concerns about the work involved were driven by assuming the migration to the v1 subdirectory was mandatory. Upon re-reading the go modules wiki page this turns out to be false. v0 and v1 get special treatment which gives a smoother migration path and doesn't create busy work.
