### ISSUE TITLE
Client cannot unmarshal struct

### ISSUE THREAD

**Issue by AlexInGitHub** [go-swagger/go-swagger#1729]
## Problem statement
Let's say, I have a struct called Pet
```go
type struct Pet{
    Type string
    Name string
}
```
I also have a struct called Person
```go
type struct Person{
    Name string
    Pet Pet
} 
```
I get the Person via API from server, the json looks like
```json
{
"name":"Alex"
"pet":null
}
```
Then I use the client of go-swagger to unmarshal the json, I will get runtime panic.
Since the field 'Type' of Pet is required in my definition.  When it unmarshal the value of 'pet', it will validate if the value of 'Type' is exist, if it's not exist, runtime panic happens.  Actually, the value is null, so the client cannot get a value for the field 'Type'.

Do you think my scenario is reasonable?

## Swagger specification
Swagger 2.0
## Environment
swagger version: 0.15.0
go version: 1.10.3
OS: Mac OS

**Comment by casualjim** [comment]
I would need to see the spec and so on. For structs we generate pointers, so in the concrete scenario you described here, it would just marshal. We don't validate responses afaik.

**Comment by casualjim** [comment]
yes it should be provided because that's how discriminators work. I don't know if that changed in 3.0

But polymorphic types all need to have their discriminator field filled out. The reason for this is that they need to be able to be located through reflection. This will be required in java, go, C#, ... 

One might be able to make a case that we should provide an implementation of the base interface too and use that as value when there is no discriminator present, although it's more likely to be a bug.

**Comment by woz5999** [comment]
I think it would be reasonable in the case of structs that have optional properties whose type is polymorphic, to do a nil check, and if nil, skip unmarshalling of that property. This respects the optional nature of the struct property without changing the discriminator behavior in the unmarshal template. 

We'd be happy to put in a PR to make this change if you agree that this is reasonable and desired.

**Comment by AlexInGitHub** [comment]
@casualjim Could we change it as @woz5999 said?

**Comment by AlexInGitHub** [comment]
I create a PR https://github.com/go-swagger/go-swagger/pull/1788
