### ISSUE TITLE
Swagger generate: can not import package

### ISSUE THREAD

**Issue by kostiamol** [go-swagger/go-swagger#1784]
## Problem statement
My project (which is in $GOPATH) is using go modules. `go build ` works without any problem.
When I execute swagger generate I receive the error: 
<img width="624" alt="capture" src="https://user-images.githubusercontent.com/5477699/47990572-869cdc80-e0f0-11e8-93e3-4c969d05f190.PNG">

## Steps to reproduce
`swagger generate spec -o swagger.yml
`
## Environment
swagger version: dev
go version: 1.11.1
OS: linux Ubuntu

**Comment by masonchu** [comment]
my workaround
`GO111MODULE=on go mod vendor`
`GO111MODULE=off swagger generate spec -o swagger.json`

**Comment by ok11** [comment]
Sounds like the project must be under GOPATH for go-swagger to work, even with go modules. Is it correct? If yes, just wondering if you are going to change it. At the end the entire story of go mods is gonna eliminate the need of the GOPATH nonsense.

**Comment by casualjim** [comment]
I'd like to change it, but I don't know when I'll have the time. My life has changed significantly from when I started this project. 
The main issue is that with go 1.11 the packages we're using have been superseded by a new set of packages to deal with the modules..

I can point you towards where we gather all the packages we want to inspect, if you're interested in fixing it.

**Comment by mcphailtom** [comment]
Please do, I'd certainly be interested in having a look

**Comment by fredbi** [comment]
@mcphailtom  FYI some early analysis was provided here #1724

**Comment by imdatngo** [comment]
In order to answer @ok11 question, and extend @masonchu solution, I can make it works with Go Modules, **outside** `GOPATH`!

The tricky part is that your entry point for `swagger generate spec` cmd must **not** contains any third-party packages! i.e it can only import your local packages! This is simple enough, just create a separate package that wraps all the logic with a `Run()` func, then import that package in your `cmd/app/main.go` and "run".

Then, to generate the spec, inside your root directory
```bash
GO111MODULE=on go mod vendor
SYMBOLIC_LINK="$GOPATH/src/$(head -n 1 go.mod | awk -F' ' '{print $2}')"
ln -s "$(pwd)" $SYMBOLIC_LINK
GO111MODULE=off swagger generate spec --scan-models -b ./cmd/app/ -o ./swagger.json
rm -f $SYMBOLIC_LINK
```

The `SYMBOLIC_LINK` is another trick! It's for the generator can still find your local packages **inside** `GOPATH`, although it's not ;)

p/s: No p/s, just link with #1724 so everyone there can see this :)
