### ISSUE TITLE
allow same operationId to be used in different endpoint

### ISSUE THREAD

**Issue by roytanmoy** [go-swagger/go-swagger#1877]
## Problem statement

Currently, to support multiple query parameters, unique paths are required for each of those parameters Allowing to use the same operationId across unique paths, will help to avoid the duplicating codes for writing multiple search functions/operationId.  

## Swagger specification
2.0
## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:

**Comment by gregmarr** [comment]
That is not allowed by the Swagger 2.0 specification.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

operationId | string | Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

**Comment by ffalor** [comment]
@casualjim I am aware operationId is unique across the whole api spec, but `go-swagger` is using operationId as a method & that is not unique. 

There isn't a reason (that I am aware of) that would prevent something like this:

`client.Tag.Query` and `client.Tag2.Query` I just ran across this because my api spec is giving an operationId of `tagQuery` resulting in very long signatures. I was using `jq` to change operationId's to something more readable, and noticed that duplicate operationId's are ignored when generating the client.

Example: A tag of `saved-searches` with a operationId of `SavedSearchesQuery` would generate into `client.SavedSearches.SavesSearchesQuery` which IMO looks/feels bad. Something like `client.SavedSearches.Query` feels more natural.
