### ISSUE TITLE
Crash when using swagger generate client

### ISSUE THREAD

**Issue by belak** [go-swagger/go-swagger#197]
I've been trying to generate code for our swaggerfile, but the generator appears to be crashing. https://bitbucket.org/!api/2.0/snippets/evzijst/78nyR/a92c1d3130a18e5031cbd452ec0303ef09165154/files/swagger.json is the swaggerfile and this is the output:

```
% swagger generate client -f swagger.json bitbucket
2016/01/07 13:18:33 building a plan for generation
2016/01/07 13:18:33 planning definitions
2016/01/07 13:18:44 planning operations
2016/01/07 13:18:58 grouping operations into packages
2016/01/07 13:18:58 planning meta data and facades
2016/01/07 13:18:58 rendered model template: paginated_issue_attachments
2016/01/07 13:18:58 rendered model template: paginated_issues
template: docstring:1:28: executing "docstring" at <.Title>: nil pointer evaluating *generator.GenSchema.Title
```

The swaggerfile is valid, according to this tool.

**Comment by casualjim** [comment]
I know what the issue is, but the fix is less than trivial. The crux of the issue is that the spec uses definitions that nest allOf with additionalProperties and discriminators and the spec nests those. 
Thanks for this spec!

**Comment by casualjim** [comment]
I've added this spec to my canary tests, meaning on every CI build it will try to generate a client and server for this specification and compile it with `go test ./...`

it would be great if you could send a [PR](https://github.com/go-swagger/go-swagger/blob/master/fixtures/canary/bitbucket.org/swagger.json) when you update your spec, so that we can be reasonably sure that we don't break bitbucket client generation again in the future.

https://github.com/go-swagger/go-swagger/blob/master/fixtures/canary/bitbucket.org/swagger.json

**Comment by belak** [comment]
Thanks! Right now our swagger support is undergoing quite a few changes, so I'll hold off on submitting updates to our swaggerfile for a bit. When it starts to stabilize, we'll get an updated swaggerfile submitted.
