### ISSUE TITLE
New scanner (go module aware) may randomly fail

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1997]
## Problem statement

* run CI suites (circleci's linux or appveyor's windows)
* test codescan TestAppScanner_NewSpec sometimes fails with panic

Looks like some underlying library is randomly failing when scanning code.

## Environment
swagger version: current master
go version: 1.12 
OS:   linux/windows

**Comment by jotak** [comment]
I'm not sure if I'm hitting the same underlying problem, but it seems now in the generated json , parameters are not sorted alphabetically anymore. Which breaks the reproducibility of generated json, which can make CIs fail if they're trying to match commited json with newly generated one.

**Comment by ajpetersons** [comment]
The description of the problem is quite sparse, but might be related - our CI has been failing to generate swagger spec since yesterday, usually failing with the following error: `can't find source file for struct: x/y/z.Z`. We have not seen this problem before, it is not always the same struct that triggers this panic, and the file is there (we are using dep).

**Comment by fredbi** [comment]
I believe the previous behavior can be forced using go1.11 (there are now 2 versions of this code scanner, since adopting go modules forced quite a lot of breaking changes)

**Comment by casualjim** [comment]
at the moment you can't force the previous behavior. @ajpetersons it would be helpful to get some more information from your failure.
The CI failing sometimes I think does indicate an issue. 

Normally the sorting of parameters should have been preserved. 
Maybe we need a transition phase and put the new scanner behind an --experimental flag.

**Comment by ajpetersons** [comment]
I'd love to provide additional information to get this fixed as soon as possible, but that is the only thing being printed out. Weirdly enough, I can't reproduce it locally, but on CI server the behavior is consistent. I'll try to see if I can work around this, in the meanwhile if there is any information that I can provide to you, I would be glad to do so.

**Comment by casualjim** [comment]
You can run `SWAGGER_DEBUG=1`

is it possible that on your local machine you have the expected type present in both your GOPATH and vendor?

**Comment by ajpetersons** [comment]
Locally I do have that file both in GOPATH and in vendor. Tried removing the copy from GOPATH, but still spec generation succeeded. 

Here is a file with output when running in debug: 
[out.log](https://github.com/go-swagger/go-swagger/files/3363684/out.log)

**Comment by casualjim** [comment]
I got a fix for the parameter ordering, which is the cause of the flaky CI run.

@ajpetersons is there a way I could look at your project and test it? If not, there are 2 other bugs #2001 and #2002 which are both public. I'll see what I can find out from those because they're also experiencing issues.

If I cant work it out on time I'll reinstate the old scanner today.

**Comment by ajpetersons** [comment]
Unfortunately, our project is private and I'm afraid that I can't share the access.

**Comment by jotak** [comment]
@casualjim If you want, you can see with Kiali, where I saw the problem last Friday. It's public:
https://github.com/kiali/kiali

There's been several builds failing, such as this one : https://travis-ci.org/kiali/kiali/builds/554552558
It's failing because we compare the generated json with the one commited and they didn't match anymore.

We've fixed our CI by sticking to a previous released version of go-swagger: https://github.com/kiali/kiali/commit/47368d5a23e262a2bf5e9a81da6618d5cc384cb4

**Comment by casualjim** [comment]
@jotak I've submitted a PR that fixes most of the differences.
There is one type in ./prometheus/types.go called Histogram that now turns into an inline definition instead of to a named one.

it uses a type alias so I'm not sure if the old behavior is actually the right one, and we may just want to stick with the new behavior

**Comment by casualjim** [comment]
that change is on master now

**Comment by jotak** [comment]
@casualjim thanks very much!
