### ISSUE TITLE
nested  $ref not found

### ISSUE THREAD

**Issue by pwmcintyre** [go-swagger/go-swagger#2113]
## Problem statement

I have a swagger spec which $ref's to another swagger spec, which $ref's a JSONSchema spec

(why? I have several repos which each implement a sub-section of my entire products API spec, so they cherry-pick sub-sections to generate code for)

The first $ref resolves fine.
The second $ref tries to resolve the path relative to the first specs location, which yields a "no such file" error

## Swagger specification

./base.yaml
```yaml
swagger: "2.0"
paths:
  /example:
    $ref: ./schemas/api/api.yaml#/paths/~1example
```

./schemas/api/api.yaml
```yaml
swagger: "2.0"
paths:
  /example:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: ../example/example.yaml
```

./schemas/example/example.yaml
```yaml
$schema: http://json-schema.org/draft-07/schema#
required:
  - payload
properties:
  payload:
    type: string
```

## Steps to reproduce

create the above files and run:
```
swagger flatten \
    --format=yaml \
    --output swagger.yaml \
            ./base.yaml
```

Error:
`could not resolve schema: open /Users/petermcintyre/git/example/example.yaml: no such file or directory`

you can see it's resolved the `../example` against the original basePath (ie. `./base.yaml`) and gone up too many directories

## Environment
swagger version: built from master (2600b738acf32bed4b094306dfbed299e870e9f3)
go version: go1.12.7 darwin/amd64
OS:   macos

**Comment by fredbi** [comment]
First take at this, trying to pinpoint the problem: I've reproduced the issue with your testcase and it looks to me the problem is actually in the `go-openapi/spec`  expander, rather than in the spec flattening: `swagger expand` and ` swagger validate` commands experience the same issue you've pointed out.
On the other hand doing ` swagger flatten schemas/api/api.yaml` just works.

**Comment by pwmcintyre** [comment]
thanks for your hard work on this!

FYI -- I've just re-run my flatten after bumping the spec package and it works fine now

ie.
```
git clone https://github.com/go-swagger/go-swagger && cd go-swagger
go get -u github.com/go-openapi/spec@master
go install ./cmd/swagger
```

**Comment by fredbi** [comment]
Ok will merge this in go swagger

**Comment by fredbi** [comment]
@pwmcintyre with some more testing, I realized the work is not complete to make it work smoothly.

You might have it running under some specific conditions, and I am glad this could unblock you, but this is still failing in the general case.

The reason is that `flatten`  by default uses the `SkipSchemas`  flattening option, which atm does not rebase the underlying `$ref`s in schemas. Still some more work on that...

**Comment by pwmcintyre** [comment]
@fredbi -- no problem

I've been wondering how you'll go about merging this in considering how it does change the way $refs work, it may be incompatible with other peoples setup ... so i totally understand

let me know if there's anything you need from me
