### ISSUE TITLE
Split files generates inconsistency across commands

### ISSUE THREAD

**Issue by codebien** [go-swagger/go-swagger#2258]
## Problem statement
I'm testing the split of a single `swagger.yml` into smaller chunks but I'm getting a not consistent behaviour between validate and generate commands.

No errors found when the validate command is run. Instead, when I execute the generate command I get the following error:
`could not resolve schema: open /go/src/github.com/codebien/definitions.yml: no such file or directory`
The generate command is researching the file into the wrong path.
The expected path is: `/go/src/github.com/codebien/swag/swagger/definitions.yml`

I have created a [repo](https://github.com/codebien/swag) to share the code.

## Swagger specification
This is the main swagger file
```
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /foo:
    $ref: 'swagger/paths/foo.yml'
  /bar:
    $ref: 'swagger/paths/bar.yml'
  /nested:
    $ref: 'swagger/paths/nested.yml#/response'
```

## Steps to reproduce
* Download the project
* Execute the validate command
* Execute the generate command

## Environment
swagger version: 0.23.0
go version: docker 0.23.0 (Go 1.14)

**Comment by fredbi** [comment]
Yes, this is the same issue as with #2137 and #2113 for $ref under paths.

I've worked on a fix for that, but this proved more complex than I thought initially (basically because we are running CI against windows and our $ref handling is a mess with windows paths...).

As a temporary solution, and if you are not running on windows (it breaks on windows), you can merge this [patch](https://github.com/go-openapi/spec/pull/111) and override the `go-openapi/spec` package with this patched version

**Comment by codebien** [comment]
Hi @fredbi, the patch works. Can I do something to speed up the merge? Do you need some contribution related to the CI?
