### ISSUE TITLE
Missing models during client generation

### ISSUE THREAD

**Issue by paddycarey** [go-swagger/go-swagger#2306]
## Problem statement

Generated client library fails to build due to missing models that aren't generated.

There's a `models` modules referenced in one of the generated files (`client/webhooks/webhooks_create_responses.go`), but it's not generated, therefore not available.

No matter what combination of command line flags I use I'm not able to generate the missing models. The spec validates successfully using `swagger validate ...` but not sure if there's perhaps something odd about it.

Any help or pointers would be greatly appreciated, thanks.

## Swagger specification

https://api.cloudsmith.io/?format=openapi

## Steps to reproduce

Create the following files:

`go.mod`

```
module github.com/cloudsmith-io/cloudsmith-go

go 1.14
```

`main.go`

```go
package main

import "github.com/cloudsmith-io/cloudsmith-go/client"

func main {
	client.New(nil, nil)
}
```

Then run:

```
curl -o swagger.json "https://api.cloudsmith.io/?format=openapi"
swagger generate client -f swagger.json
go build
```

Results in the output:

```
go: finding module for package github.com/go-openapi/strfmt
go: finding module for package github.com/go-openapi/runtime
go: finding module for package github.com/go-openapi/swag
go: finding module for package github.com/go-openapi/runtime/client
go: finding module for package github.com/go-openapi/errors
go: finding module for package github.com/cloudsmith-io/cloudsmith-go/models
go: finding module for package github.com/go-openapi/validate
go: found github.com/go-openapi/runtime in github.com/go-openapi/runtime v0.19.15
go: found github.com/go-openapi/strfmt in github.com/go-openapi/strfmt v0.19.5
go: found github.com/go-openapi/errors in github.com/go-openapi/errors v0.19.4
go: found github.com/go-openapi/swag in github.com/go-openapi/swag v0.19.9
go: found github.com/go-openapi/validate in github.com/go-openapi/validate v0.19.8
go: finding module for package github.com/cloudsmith-io/cloudsmith-go/models
client/webhooks/webhooks_create_responses.go:19:2: cannot find module providing package github.com/cloudsmith-io/cloudsmith-go/models: module github.com/cloudsmith-io/cloudsmith-go/models: git ls-remote -q origin in /Users/paddy/go/pkg/mod/cache/vcs/b2f1ca9505e5604c8ac0e6d8cf2590175ec860c989e60b0f5ea99e975f9207be: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

## Environment
swagger version: v0.23.0
swagger commit: 3596b40bedd4f06cc918767098568456d2ec2370
swagger container: quay.io/goswagger/swagger:v0.23.0
go version: go version go1.14.3 darwin/amd64
OS:  OSX 10.13.6

**Comment by fredbi** [comment]
@paddycarey  it looks from your spec that all schemas are inlined with the paths definitions. In situations like this, goswagger sets out to generate all inlined things in the `operations` package rather than in `models`.

The fact that there is still a reference to some model package looks like a bug. Needs to be investigated - your spec is quite large... -.

As a workaround, you might give a try to the `--with-flatten=full`  option which externalizes inlined objects to definitions, hence models.

**Comment by fredbi** [comment]
@paddycarey  I've investigated your issue over the last (rainy) weekend and it stems for a name conflict when generating the anonymous structures (aka inline).
This is an interesting spec, but it looks like it will be difficult to use to develop a server, since all models are anonymous, hence no structure sharing. To an external eye, it looks like this spec has been generated and expanded.

Nevertheless, go-swagger should be able to process it and this is a bug.

As far as I can see, there is only one set of operations that is sensitive to this bug: in webhooks, all operations define an inline array `Templates`.  The generation of the items structures in the `operations/webhooks` package 

A proper way to work around this would be to define the common definition of the template items under "definitions" and refer to it with something like "$ref": "#/definitions/TemplateItems".
Renaming the different "templates" with different names also works...

So now you have a workaround. The bug is indeed complex to solve.

**Comment by paddycarey** [comment]
Hi @fredbi, thanks for looking into this, it's really helpful!

> This is an interesting spec, but it looks like it will be difficult to use to develop a server, since all models are anonymous, hence no structure sharing. To an external eye, it looks like this spec has been generated and expanded.

In this case we're only trying to generate a client, so hopefully no issues with server generation, though I understand the concern. The spec is generated from a custom Django Rest Framework setup, which we're in the process of updating to be closer to mainline, so hopefully that will resolve some of the weirdness with the spec.

Thanks for the workarounds, I'll check them out. The PR also looks promising, i'll check that out too.

Thank you for your work here, it's much appreciated!
