### ISSUE TITLE
Raw request body is empty if we try get it inside handler function

### ISSUE THREAD

**Issue by SlavaValAl** [go-swagger/go-swagger#2310]
## Problem statement
When I'm trying to get raw POST request body inside handler function I always get it empty.
`
func (h *Handler) HandlerExample(params swg.Params) middleware.Responder {
     // params.HTTPRequest.Body <- empty ReadCloser there
}
`
As far as I understand, swagger read bytes from request body to fill body structure described in spec and do not replace request Body with new ReadCloser( see example in https://golang.org/src/net/http/httputil/dump.go -> drainBody function).

## Swagger specification

swagger: "2.0"
info:
  title: Any Title
  description: Any App
  version: 1.0
host: localhost
schemes:
  - http
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /any/route:
    post:
      summary: any summary
      operationId: anyOperationID
      parameters:
        - description: Any description
          in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              content:
                type: string
                description: Any content
                minLength: 1
            required:
              - content

## Steps to reproduce
I think I already described it in statement section.

## Environment
swagger version: v0.21.0
go version: go1.14.1 darwin/amd64
OS:  Mac OS Mojave Version (10.14.6)

**Comment by Sef1995** [comment]
+1

**Comment by casualjim** [comment]
Yes we already consumed the body, because your spec should describe your inputs and outputs. we provide the request because sometimes people have stuff in headers that's not described in the spec and for access the context that was put on the request. But caching a body stream is not something we want to because they are of undefined size. if you want to do that you can do that in a middleware that executes before the swagger stuff.
