### ISSUE TITLE
Fails to generate client for star trek api http://stapi.co/

### ISSUE THREAD

**Issue by richardwooding** [go-swagger/go-swagger#2443]
## Problem statement

Fails to generate client for star trek api http://stapi.co/

Returns this error
```
2020/11/25 13:54:42 validating spec /Users/richardwooding/sandbox/stapi-spec/stapi.yaml
The swagger spec at "/Users/richardwooding/sandbox/stapi-spec/stapi.yaml" is invalid against swagger specification 2.0. see errors :
- some references could not be resolved in spec. First found: object has no key "definitions"
```

## Swagger specification

It's big, a [zip file](http://stapi.co/api/v1/rest/common/download/zip/rest) can be downloaded here.

## Steps to reproduce

Assuming you have docker, wget, and unzip installed

```
docker pull quay.io/goswagger/swagger
alias swagger="docker run --rm -it -e GOPATH=$HOME/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
mkdir -p ~/sandbox/stapi-spec
mkdir -p ~/sandbox/stapi-client
cd ~/sandbox/stapi-spec
wget http://stapi.co/api/v1/rest/common/download/zip/rest -O rest.zip
unzip rest.zip
cd ~/sandbox/stapi-client
swagger generate client -f ~/sandbox/stapi-spec/stapi.yaml -A stapiclient
```

## Environment
swagger version: v0.25.0
go version: go1.15.3 darwin/amd64
OS:  Mac OS X (docker)

**Comment by fredbi** [comment]
@richardwooding Even though I don't like star trek one bit, I've taken a quick look at the spec.

It seems to me that there is a misunderstanding of what $ref means in this spec.
I've found documents that point to '#/definitions/...'  but there is no definition in the same root.

Example: `./spacecraft/path/spacecraft.path.yaml`
I see there:
```
      description: API key
  responses:
    200:
      schema:
        $ref: '#/definitions/SpacecraftFullResponse'
```
When it should be:
```
$ref: '../../stapi.yaml#/definitions/SpacecraftFullResponse`
```
In other words, the `$ref` in this set of files does not follow the semantics of jsonschema `$ref`.

It seems that this set of yaml has to be pre-processed and reassembled to match something that looks like correct $ref.

**Comment by richardwooding** [comment]
Thanks for the analysis, I will let @cezarykluczynski of https://github.com/cezarykluczynski/stapi know that the swagger spec is not using $ref correctly.

**Comment by richardwooding** [comment]
Since this is not an issue with go-swagger, I am closing this issue.

**Comment by cezarykluczynski** [comment]
Hi, @fredbi, regarding this error:

```- some references could not be resolved in spec. First found: object has no key "definitions"```

There is a definition object in the root yaml file:

https://github.com/cezarykluczynski/stapi/blob/master/contract/src/main/resources/v1/swagger/stapi.yaml#L172

Do you have an idea why isn't it picked correctly?

**Comment by fredbi** [comment]
@cezarykluczynski  hello
With jsonschema, with each schema corresponds a "namespace", or root of the document.

Therefore, references such as '#/definitions/xxx' points to this document.

We consider stapi.yaml and (for example) ./spacecraft/path/spacecraft.path.yaml to be 2 different documents.
A reference '#/definitions/xxx' in spacecraft.path.yaml looks for a definition key in _this_ document, not in stapi.yaml

That's why I said above that this needs some preprocessing to be valid: you are defining references in a single namespace,
that is a single schema.
I believe that this would work if the root references would be, instead of json reference, mere yaml doc expanders. In that case, yaml would expand the various files into one single json schema and this would work.
