### ISSUE TITLE
Using minItems not generating correct validation code

### ISSUE THREAD

**Issue by omrihq** [go-swagger/go-swagger#2597]
## Problem statement
Using minItems generates validation for minimum number of items, but doesn't include the name of the path, which is required for verbose errors

## Swagger specification
```
paths:
  /v1/blah:
    patch:
      produces:
        - application/json
      parameters:
        - name: newArray
          in: body
          schema:
            $ref: '#/definitions/BlahArray'

definitions:
  BlahArray:
    description: The array of blah numbers
    type: array
    items:
      type: integer
    minItems: 1
```

## Output

```
// In file blah_array.go
type BlahArray []int64

// Validate validates this blah array
func (m Blah) Validate(formats strfmt.Registry) error {
	var res []error

	iBlahArraySize := int64(len(m))

	if err := validate.MinItems("", "body", iBlahArraySize, 1); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
```

Notice: `validate.MinItems("", "body", iBlahArraySize, 1);`, which results in error copy such as `" in body should have at least 1 items"` 

Expectation would be: `validate.MinItems("BlahArray", "body", iBlahArraySize, 1);`, which would return `"BlahArray in body should have at least 1 items"` or something

## Environment
swagger version: 2.0
go version: 1.15
OS: macOS

Thanks for maintaining this library, it is a joy to use

**Comment by fredbi** [comment]
This issue is not specific to ` MinItems`: all validations are affected. It affects models that represent arrays or maps.
For all those models, the path is empty. Path is used effectively for parameters, responses and headers and for properties in `struct`s that represent objects.

Therefore, the above expectation is difficult to meet without breaking a lot of the logic in how that path reported in validations errors is constructed.

Here is a proposal (see forthcoming PR): expose an option to build models (e.g. `--rooted-error-path`   that enables the above expectation. Specifically for arrays and maps, we can replace the empty path by the name of the type.

Here how it would look like in your example (I've added another validation to show that this is not limited to `minItems` ):
```go 
// BlahArray The array of blah numbers
//
// swagger:model BlahArray
type BlahArray []int64

// Validate validates this blah array
func (m BlahArray) Validate(formats strfmt.Registry) error {
        var res []error

        iBlahArraySize := int64(len(m))

        if err := validate.MinItems("[BlahArray]", "body", iBlahArraySize, 1); err != nil {
                return err
        }

        if err := validate.UniqueItems("[BlahArray]", "body", m); err != nil {
                return err
        }

        if len(res) > 0 {
                return errors.CompositeValidationError(res...)
        }
        return nil
}

````

Similarly for maps:
with 
````yaml
BlahMap:
    description: this is a map[string]string
    type: object
    additionalProperties:
      type: string
    maxProperties: 10
````
one may get:
```go
// BlahMap this is a map[string]string
//
// swagger:model BlahMap
type BlahMap map[string]string

// Validate validates this blah map
func (m BlahMap) Validate(formats strfmt.Registry) error {
        var res []error

        nprops := len(m)

        // maxProperties: 10
        if nprops > 10 {
                return errors.TooManyProperties("[BlahMap]", "body", 10)
        }

        if len(res) > 0 {
                return errors.CompositeValidationError(res...)
        }
        return nil
}
````
