### ISSUE TITLE
request Content-Type isn't multipart/form-data

### ISSUE THREAD

**Issue by EricLau1** [go-swagger/go-swagger#2773]
## Problem statement

I`m trying upload a file from go generated client, but when I submit the file, the service responds with error:

>ERROR: request Content-Type isn't multipart/form-data

## Swagger specification

```json
"/api/my-route": {
    "post": {
      "security": [
        {
          "auth": [
            "default"
          ]
        }
      ],
      "consumes": [
        "multipart/form-data",
        "application/x-www-form-urlencoded"
      ],
      "produces": [
        "application/octet-stream",
        "application/json"
      ],
      "tags": [
        "my-tag"
      ],
      "operationId": "OperationName",
      "parameters": [
        {
          "type": "string",
          "description": "multipart/form-data",
          "name": "Content-Type",
          "in": "header"
        },
        {
          "type": "file",
          "description": "",
          "name": "file",
          "in": "formData"
        }
      ],
      "responses": {
        "200": {
          "description": "",
          "schema": {
            "$ref": "#/definitions/MyDef"
          }
        },
        "400": {
          "description": "bad payload",
          "schema": {
            "$ref": "#/definitions/MyDefError"
          }
        },
        "401": {
          "description": "invalid credentials",
          "schema": {
            "$ref": "#/definitions/MyDefError"
          }
        }
```

## steps to reproduce

Generated code in my client side:

```go
type UploadFileParams struct {

	/* ContentType.

	   multipart/form-data
	*/
	ContentType *string

	/* File.

	*/
	File runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}
```

then, I load a file as `io.Reader` and set in params:

```go
        contentType := "multipart/form-data"

	params := &UploadFileParams{
		ContentType: &contentType,
		File:        runtime.NamedReader("file", reader),
		Context:     ctx,
	}
```

Code in my server side:

```go
func MyHandler(w http.ResponseWriter, r *http.Request) {
	file, _, err := r.FormFile("file")
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	data, err := ioutil.ReadAll(file)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
       ....
}
```

## Environment
swagger version: v0.28.0
go version: go1.18.2
OS: darwin/amd64

**Comment by fredbi** [comment]
A few comments on that issue.

1. It is futile to override the Content-Type header this way: it is overridden by the client runtime based on the "consumes" mime types
2. Everything works just fine if the operation declares only one "consumes": "multipart/form-data" (see a working example: https://github.com/go-swagger/go-swagger/tree/master/examples/file-server)
3. The problem comes from the two "consumes" types specified:
   * problem N°1: the order of the mime types for the client is reversed. So it picks primarily "application/x-www-form-urlencoded", which was not intended
   * problem N°2: although the swagger 2.0 states that files _may_ be transferred over "application/x-www-form-urlencoded", our client runtime (go-openapi/runtime/client) does not support that (because it is not the _preferred_ way) and results in a mismatch: sending a multipart body with Content-Type: "application/x-www-form-urlencoded"

It is possible to work around this problem by forcing the MIME type in the operation by using an option.
Like so:
```go
dummyAuth := runtime.ClientAuthInfoWriterFunc(func(_ runtime.ClientRequest, _ strfmt.Registry) error {
		return nil
	})
forceMime := func(mime string) my_tag.ClientOption {
		return func(r *runtime.ClientOperation) {
			r.ConsumesMediaTypes = []string{mime}
		}
	}

const content = "content of this file"
			rdr := strings.NewReader(content)
			params := my_tag.NewOperationNameParams().
				WithFile(runtime.NamedReader("file", rdr))
			resp, err := c.MyTag.OperationName(params, dummyAuth, forceMime(contentType))
````

**Comment by fredbi** [comment]
There are a few ways we could improve this situation:
* generate a `UseMIME(...)` option with the client, so that the caller may switch easily when several mimes are consumed
* support application/x-www-form-urlencoded for files in runtime (this would be workable only for small files, and we'd lose the ability to stream). This would make the runtime 100% compliant with the spec, but with little practical use (IMHO).
