### ISSUE TITLE
Refactor package structures

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#420]
There are a number of packages that are more like libraries, they would be better extracted.

Perhaps it's a good thing to extract these into their own repos. The CLI command can then vendor each of those repos. Most of them are stable at this point.

specs, jsonreference, jsonpointer, scan, swag and the httpkit

**Comment by pytlesk4** [comment]
Would love to see this happen, and help out where I can.  We use go-swagger currently at [http://stoplight.io/](url), and when I was evaluating it, I almost passed it up because we were looking for a way to just parse and load a swagger file.

If everything were to be broken up into libraries, I feel like it would be a lot more approachable.  Go-Swagger can do a lot of cool things, and navigating the source code was daunting.  One day Stoplight might do code generation, for apis, but because we don't need that now I almost passed on this awesome project.  I have submitted a few pull requests to fix some issues in the spec package, and even though all the tests were passing in the spec package, my changes broke some tests in another packaged that I knew nothing about.

That is all for now.

**Comment by phedoreanu** [comment]
It would be nice to serve swagger-ui in a more user-friendly way. 

Also, for better compatibility with the Docker `go-wrapper` command, can `main.go` be moved in the root `$projectFolder` i.e. `test/test-api/main.go` from `test/test-api/cmd/test-server/main.go`?

Docker build errors: 
 * `can't load package: package test/test-api: no buildable Go source files in /go/src/test/test-api`
 * `can't load package: package test/test-api/cmd/test-server: no buildable Go source files in /go/src/test/test-api/cmd/test-server`

**Comment by emicklei** [comment]
I am the author of the [swagger2](https://github.com/emicklei/swagger2) package which is intended to be a rewrite/upgrade of [go-restful/swagger](https://github.com/emicklei/go-restful/tree/master/swagger).

The goal of this swagger2 project is to separate the Swagger part from the REST part, allowing others to use the package independently by provinding only the specification objects. I was planning to create another (sub?) package for building model objects from Go types (as I already created 1.2).

As discussed offline with one of the authors of go-swagger, I would like to see go-swagger to be split into multiple repos for the most part because of handling the dependencies. Applications that import go-swagger (using vendoring) should not be forced to include the whole package deal (e.g. generators).

If the go-swagger project would separate the spec part into a new repo then I will probably drop my swagger2 project and collaborate on that instead.

**Comment by casualjim** [comment]
This repository should only contain the code that is directly used by the executable. Things that are being used as library constructs will move into their own stand-alone packages.

I want to squash several issues here:

1. move the yaml dependency out into packages so that it doesn't automatically turn your application into an LGPL application and swagger (executable) can be classified as a build tool.
2. turn the swag package into its own repo
3. move jsonpointer package to its own repo
4. move jsonreference package to its own repo 
5. separate spec package into a 2 repos:
    1. the spec object model
    2. analysis package that takes care of analyzing swagger specifications and provides an index to be used by other packages.
6. move validation into its own repo
7. move examples to their own repo
8. move httpkit into its own repo

These repos will get created under the go-openapi org instead of the go-swagger org due to the rename of the specification.

**Comment by casualjim** [comment]
I've begun work on this, might not be exactly what I laid out in the previous comment but it will be close. I hope it won't take me longer than a weekend to complete this.

**Comment by ontucker** [comment]
I commented about this on another issue but I'm not sure if you saw it, so I'll repeat it here.  What I'd really like to see is a structure of generated code that allows it to stay as a completely standalone module that requires no editing of the files within.  I have taken to simply ignoring most of the generated `main()`, `configure_xyz.go`, and `server.go` code and duplicating their functionality in external modules in order to avoid the mess that occurs when I regenerate from the spec and the structure of files I've edited has changed (regarding edits due to go-swagger changes, not necessarily due to changes to my spec).  It's much easier to regenerate from the spec and then diff that entire tree with the knowledge that I'm only looking at differences in generated code, not adding in the complications of my hand-edits.

So my recommendation is that the entire `cmd` directory, as well as `configure_xyz.go` and `server.go` be factored out into a separate "example" directory to indicate how you _could_ use the generated code, but with the expectation that people are _actually_ going to integrate the generated code into a codebase that doesn't necessarily follow that structure.

**Comment by casualjim** [comment]
ontucker yes I got that requirement. this is about the go-swagger codebase itself.
For your requirement I think the server that gets generate will get an interface passed in with 3 hooks for lifecycle events: starting/configuring/stopping

I like the example suggestion

**Comment by ontucker** [comment]
Oh, yeah, I meant to throw in a comment to the effect that "this may not be specifically relevant to this issue, but so long as you're reorganizing things I want to mention it so you have it in mind while moving things around."  :)  Thanks.

**Comment by casualjim** [comment]
I've moved most of the supporting code for to command to separate repos as well as applied a restructuring for yaml

The only thing I didn't do was remove the examples from this repo, because I think they are still kind of appropriate in this repo.
