### ISSUE TITLE
escaped slashes in path ids are incorrectly decoded

### ISSUE THREAD

**Issue by franshamk** [go-swagger/go-swagger#522]
## Problem statement

Forward slashes in urlencoded path parameters are treated as route separators. 

- I have a route: /api/{id}
- the id contains a forward slash, so id = "abc/def"
- url encode the id, to become id = "abc%2Fdef"
- swagger incorrectly gives the error 'path /api/abc/def not found'

This is a big issue for us, because we have to ask the consumers of our API to use special encoding logic for their path parameters if they contain a slash. 

## Swagger specification

2.0

## Steps to reproduce

 - url encode a parameter with a slash. 
 - issue curl request: curl 'http://api_host/api/abc%2Fdef'
 - observe 'path /api/abc/def not found error'

**Comment by mingderwang** [comment]
curl:  is not correctly encode URL for " !== "

%20&#33;%3D%3D%20

Request URL:    is correctly encode URL for " !== "
%20!%3D%3D%20

**Comment by vedantsethia-infoblox** [comment]
Some of my APIs use a file path as the path parameter (Ex. .../hello/test.txt) which will include a forward slash. However in Swagger, it always escapes the forward slash such that my intended URL of

/api/v1/hello/test.txt

becomes

/api/v1%2Fhello%2Ftest.txt which throws errors because it's not a valid URL.

Is there any way to work around this? From what I understand is that they don't plan on putting a fix to this even in future releases of Swagger.
