### ISSUE TITLE
Access http status code from client

### ISSUE THREAD

**Issue by myles-mcdonnell-m3** [go-swagger/go-swagger#597]
I have been unable to determine how to access the HTTP Status code of a response using the auto gen client..apologies if this is in the docs or sample code and I have just failed to find it.

**Comment by myles-mcdonnell-m3** [comment]
I'm getting quite a number of issues using the autogen client code, beginning to suspect it's early day for this piece and I should hand a roll a client for now.  Is this a fair comment?

**Comment by casualjim** [comment]
swagger doesn't deal with http, it deals with the contracts on top of them and considers http the transport but it's just an implementation detail to the contract.

Before I answer the question about the status code, can you please share  a spec with at least one representative operation defined.

the default response structure captures the status code but if you have other responses you'll get a type, which in turn implies the status code. eg. OKResponse implies 200 no need to carry that around the type already means 200 OK.

like this one is a response struct for a 200 status code in the spec: https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/client/todos/find_responses.go#L51

Then this one is the default response: https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/client/todos/find_responses.go#L80

Because it's not specified with a status code you have a Code() accessor on that instance which gives you the status code

**Comment by myles-mcdonnell-m3** [comment]
Operation spec:

```
post:
  parameters:
    -
      in: body
      required: true
      name: client
      schema:
        $ref: "#/definitions/client"
  responses:
    200:
      description: "Create new client"
      schema:
        $ref: "#/definitions/client"
    401:
      description: "unauthorised"
    default:
      description: "generic error response"
      schema:
        $ref: "#/definitions/errorMessage"
  tags:
    - clients
```

Client def:

```
properties:
  id:
    format: int64
    type: integer
  name:
    type: string
required:
  - id
  - name
type: object
```

Integration test code:
```
func TestCreateOneOk(t *testing.T) {

	id := int64(0)

	client := &models.Client{ID: &id, Name: SPtr("New Client")}

	response, err := Apiclient.Clients.PostClients(clients.NewPostClientsParams().WithClient(client)) //Returns (*PostClientsOk, error)

	if err != nil {
		t.Fatal(fmt.Sprintf("Error: %s", err.Error()))
	}

	payloadJson, _ := json.Marshal(response.Payload)
	errorJson, _ := json.Marshal(response.Error())

	log.Print(string(payloadJson))
	log.Print(string(errorJson))

}
```

Request / Response

```
POST /clients HTTP/1.1
User-Agent: Go-http-client/1.1
Content-Length: 29
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip
Host: localhost:4004

{"id":0,"name":"New Client"}


HTTP/1.1 200 OK
Content-Type: application/json
Vary: Origin
Date: Wed, 27 Jul 2016 14:30:58 GMT
Content-Length: 32

{"id":1040,"name":"New Client"}
```

Output from test:
```
2016/07/27 15:26:41 {"id":1039,"name":"New Client"}
2016/07/27 15:26:41 "[POST /clients][200] postClientsOK  \u0026{ID:0xc82021e9a8 Name:0xc82021e9c0}"
```

So I have 2 questions; 1) as the Apiclient.Clients.PostClients(..) method returns *PostClientsOk how could it return the other types that are bound to/represent different HTTP status codes. 2) what is the purpose of the error string?

**Comment by casualjim** [comment]
1. PostClientsOK is the success case, typically there is only 1 response that means success. So we generate a method that in case of a 2xx response we return that type.
2. The`Error() string` method makes it so that non 2xx responses (error responses), implement the golang error interface. So when a request isn't successful (non-2xx) then you get an error instead of a success case. Because certain responses are typed you can use a type switch to determine what happened

**Comment by myles-mcdonnell-m3** [comment]
Got it, that all makes sense now.  Thank you for your patience.

**Comment by myles-mcdonnell-m3** [comment]
That all makes sense now.  Thank you for your patience.

**Comment by taojwmware** [comment]
I am writing transport wrapper to auto-retry Submit for some error code. Without error code, there is not generic solution to write a wrapper. It will end up with enumerating all the higher level errors representing exactly the same http status code, for example: 404.

**Comment by taojwmware** [comment]
The example for default response is special: https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/client/todos/find_responses.go#L80
type FindDefault struct {
	_statusCode int

	Payload *models.Error
}
because it has _statusCode. However, if any status code also defined/mapped in swagger, the _statusCode field is gone. There is no way to get the status code in such case.

**Comment by casualjim** [comment]
you can write a custom round tripper where you have access to the response. This will allow you to do retries

https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L185
https://github.com/golang/go/blob/go1.9/src/net/http/client.go#L139

**Comment by taojwmware** [comment]
It works now. Thanks for your help!

**Comment by Miroku87** [comment]
> It works now. Thanks for your help!

Can you please provide an example code?
Thank you!

**Comment by jeffreydwalter** [comment]
@casualjim 
> 1. PostClientsOK is the success case, typically there is only 1 response that means success. So we generate a method that in case of a 2xx response we return that type.
> 2. The`Error() string` method makes it so that non 2xx responses (error responses), implement the golang error interface. So when a request isn't successful (non-2xx) then you get an error instead of a success case. Because certain responses are typed you can use a type switch to determine what happened

Can you please provide a quick example of handling a 404 response? In the example in this issue, are you saying that I should switch on `PostClientsOK` or on `err` to determine whether the error was a 404 or not? Thanks!

**Comment by fredbi** [comment]
```go
if _, notFound := err.(*operations.PostClientsNotFound) ; notFound {
  log.Prinf("resource not found")
}
```
