### ISSUE TITLE
How to serve the API from a Docker container?

### ISSUE THREAD

**Issue by Ravenwater** [go-swagger/go-swagger#751]
## Problem statement

I am trying to serve a go-swagger generated API from a container, and get an ERR_EMPTY_RESPONSE.

## Swagger specification
tutorials/todo-list/server-complete/swagger.yml

## Steps to reproduce
Dockerfile: I have copied server-complete to a standalone repo and vendored it so that the build can occur in the container.

```Dockerfile
FROM golang
MAINTAINER E. Theodore L. Omtzigt 

ENV GOBIN $GOPATH/bin

ADD . /go/src/github.com/Ravenwater/server-complete
RUN go install /go/src/github.com/Ravenwater/server-complete/cmd/todo-list-server/main.go
WORKDIR /go/src/github.com/Ravenwater/server-complete
ENTRYPOINT /go/bin/main --port 8090

# serving HTTP of 8090
EXPOSE 8090
```

**Comment by casualjim** [comment]
Try this

```Dockerfile
FROM golang
MAINTAINER E. Theodore L. Omtzigt 

ENV GOBIN $GOPATH/bin

ADD . /go/src/github.com/Ravenwater/server-complete
RUN go install /go/src/github.com/Ravenwater/server-complete/cmd/todo-list-server
WORKDIR /go/src/github.com/Ravenwater/server-complete
ENTRYPOINT /go/bin/todo-list-server --port 8090 --host 0.0.0.0

# serving HTTP of 8090
EXPOSE 8090
```

**Comment by Ravenwater** [comment]
Perfect, that works.

What is the explanation?

**Comment by casualjim** [comment]
by default goswagger servers default to localhost, this is done so that on osx it doesn't trigger the firewall popup when you test. Also it's safer to not listen on all interfaces by default.
Inside a docker container we do want to listen on all interfaces because localhost there refers to the docker container itself. 

then the other edit is the go install without the main.go. The only time you need to refer to files directly is when you use go run, for go install you can refer to the package that contains the main and then the binary will be named the same as the folder (package).

For a slightly more advanced (and a lot smaller container) you can also use a 2 stage compilation process, You use 1 container to build the binary and and another container to run the binary.

You can run the build.sh script below. Unfortunately I've never tried this on windows though, I think your best bet there is to use powershell. (or perhaps try the windows linux subsystem). The files i included below are also available here: https://github.com/casualjim/testapp

For a folder called testapp in the gopath with the following files in it:

Dockerfile:
```Dockerfile
FROM casualjim/base:latest
MAINTAINER Ivan Porto Carrero <ivan@flanders.co.nz> (@casualjim)

ADD testapp /testapp
EXPOSE 8080
ENTRYPOINT ["/testapp"]
```

build.sh
```shell
#!/bin/bash

set -e -o pipefail

version=${1-"latest"}

brwhte="$(tput setaf 15)"
bryllw="$(tput setaf 11)"
creset="$(tput sgr0)"
yarrow="${bryllw}=>${creset}"

build_binary() {
  set -u
  echo -e "${yarrow} building binary ${brwhte}testapp${creset}"
  docker pull casualjim/builder
  docker run --rm -it -v `pwd`:/go/src/github.com/casualjim/testapp -w /go/src/github.com/casualjim/testapp  casualjim/builder "$@"
}

build_container() {
  set -u
  echo -e "${yarrow} publishing ${brwhte}testapp${creset}"
  docker build --pull --no-cache -q -t casualjim/testapp:$version .
}

build_binary go get ./... && go build -o testapp -a -ldflags '-w -linkmode external -extldflags "-static"' .
build_container

```

main.go:
```go
package main

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"net/http/httputil"
	"time"

	"github.com/tylerb/graceful"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		b, err := httputil.DumpRequest(req, false)
		if err != nil {
			log.Printf("handle request: %v", err)
		}
		log.Printf("%s", b)
		fmt.Fprintf(w, "Welcome to the home page!")
	})

	httpServer := &graceful.Server{Server: new(http.Server)}
	httpServer.SetKeepAlivesEnabled(true)
	httpServer.TCPKeepAlive = 3 * time.Minute
	httpServer.ListenLimit = 50
	httpServer.Timeout = 10 * time.Second
	httpServer.Handler = mux
	httpServer.Logger = graceful.DefaultLogger()

	tcpv4Listener, err := net.Listen("tcp4", ":8080")
	if err != nil {
		log.Fatalln(err)
	}

	log.Println("serving on", tcpv4Listener.Addr().String())
	if err := httpServer.Serve(tcpv4Listener); err != nil {
		log.Fatalln(err)
	}
}
```

**Comment by casualjim** [comment]
yeah the build script is specifically for building against a musl based linux in a docker container

**Comment by hunterBhough** [comment]
For anyone coming across this in the future, host takes a string, so use --host="0.0.0.0" instead of --host=0.0.0.0     ... port takes an int
example:
```
FROM golang
MAINTAINER E. Theodore L. Omtzigt 

ENV GOBIN $GOPATH/bin

ADD . /go/src/github.com/Ravenwater/server-complete
RUN go install /go/src/github.com/Ravenwater/server-complete/cmd/todo-list-server
WORKDIR /go/src/github.com/Ravenwater/server-complete
ENTRYPOINT /go/bin/todo-list-server --port 8090 --host="0.0.0.0"

# serving HTTP of 8090
EXPOSE 8090
```
