### ISSUE TITLE
Server codegen and "target must reside inside a location in the $GOPATH/src"

### ISSUE THREAD

**Issue by SandyWalsh** [go-swagger/go-swagger#754]
## Problem statement

go-swagger complains target not in $GOPATH when, I think, it is ...

```
$ echo $GOPATH
/home/sandy/go

$ pwd
/home/sandy/go/src/my_org/my_project

$ alias swagger="docker run --rm -it -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
$ alias
...
alias swagger='docker run --rm -it -v /home/sandy:/home/sandy -w /home/sandy/go/src/my_org/my_project quay.io/goswagger/swagger'

$ ls -la subdir/spec/
...
-rw-rw-r-- 1 sandy sandy 10116 Oct 31 15:26 project.swagger.yaml

$  swagger generate server -f subdir/spec/mosaic.swagger.yaml -t output
2016/11/24 17:16:22 building a plan for generation
2016/11/24 17:16:22 target must reside inside a location in the $GOPATH/src


```

But ... but ... it is?

**Comment by casualjim** [comment]
Can you change your alias a little?

I think either of these should work:

```
alias swagger='docker run --rm -it -v /home/sandy:/root -v /home/sandy/go:/go -w /go/src/my_org/my_project quay.io/goswagger/swagger'
```

or

```
alias swagger='docker run --rm -it -e GOPATH=/home/sandy/go:/go -v /home/sandy:/home/sandy -w /home/sandy/go/src/my_org/my_project quay.io/goswagger/swagger'
```

**Comment by casualjim** [comment]
The explanation is that while on your local machine the project definitely resides in the go path, but the go path in the docker container is at /go not at your home directory.
There are also a  few items pre-installed in the gopath of the container you're using so that also makes it so you can't fully overwrite the go path with yours.
It is possible though but then you have to make sure you have these packages in your local go path (and compiled for linux not another OS) https://github.com/go-swagger/go-swagger/blob/master/Dockerfile#L5-L10

**Comment by SandyWalsh** [comment]
Awesome ... works like a charm. 

Thanks @casualjim!
