### ISSUE TITLE
client uuid/string type mismatch

### ISSUE THREAD

**Issue by SandyWalsh** [go-swagger/go-swagger#789]
## Problem statement

Seems the gen'ed client code has a problem with UUID types.

```
client/client/operations/get_mosaic_experimental_series_series_id_mosaics_parameters.go:103: cannot use o.SeriesID (type strfmt.UUID) as type string in argument to r.SetPathParam
client/client/operations/get_mosaic_experimental_series_series_id_parameters.go:103: cannot use o.SeriesID (type strfmt.UUID) as type string in argument to r.SetPathParam
```

the path is of the form
```
/mosaic/experimental/series/{SeriesId}/mosaics
```

which may have something to do with it. 

## Swagger specification
https://gist.github.com/SandyWalsh/5987303142bea7bf5d41c07476dccf76

**Comment by xtoddx** [comment]
Hey @SandyWalsh!

You can work around this locally by copying in the client/parameters.gotmpl to your local project and specifying the --template-dir flag. You can change the SetPathParam line to:
```
  if err := r.SetPathParam({{ printf "%q" .Name }}, {{ if .Formatter }}{{ .Formatter }}({{ if .IsNullable }}*{{end}}{{ .ValueExpression }}){{ else }}{{if eq .GoType "strfmt.UUID" }}string({{end}}{{ if .IsNullable }}*{{end}}{{ .ValueExpression }}{{ if eq .GoType "strfmt.UUID" }}){{end}}{{end}}); err != nil {
```

As far as upstream fixes go, I have some suggestions but I'm not sure the right/best way so I'll just leave my ideas here as notes to the maintainers:

I hacked around in generator/types.go and added `"strfmt.UUID": "string"` to the `stringFormatters` map which worked perfectly w/o changing the template (where perfectly means it built for this one particular case).  It would be nice if the atomic `string` type implemented `fmt.Stringer` (as strfmt.UUID does) so that go-openapi/runtime could take a fmt.Stringer as the second param of SetPathParam -- or SetPathParam could take an empty interface and try to cast to string/fmt.Stringer/etc in turn.

**Comment by SandyWalsh** [comment]
Hey @xtoddx ... a great voice to hear from the wilderness! 

If the manual edits get to be too much I'll look at copying the templates. Thanks for that. 

I can see that if we're going to keep using this library I'm going to need to get my hands dirty in the implementation. Thanks for steering me in the general direction.  :)

**Comment by casualjim** [comment]
which version of swagger are you using? because I'm having a hard time reproducing this issue.
https://github.com/go-swagger/go-swagger/pull/806

**Comment by SandyWalsh** [comment]
```
$ swagger version
version: 0.7.4
commit: 8f0d4bb6fc08d6b4bf2826cd4e13d7dce32c104c
```

One of my colleagues noticed that the 0.7.4 sha from the docker image differs from the 0.7.4 image in the repo.

**Comment by casualjim** [comment]
I've confirmed that the issue exists in 0.7.4 and is gone on master

**Comment by casualjim** [comment]
I created a 0.8.0 release, so you have a stable version to depend on
https://github.com/go-swagger/go-swagger/releases/tag/0.8.0
