### ISSUE TITLE
responses dont have a stable order

### ISSUE THREAD

**Issue by claasstoertenbecker** [go-swagger/go-swagger#846]
## Problem statement

When generating a client-sdk two times from the same spec responses dont have a stable order.
https://github.com/claasstoertenbecker/go-esi-link/commit/69176ecb74bcbb9f0a248458efa4b4eab9fb996c

## Swagger specification
https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility

## Steps to reproduce
1.) generate client sdk from spec
2.) do it again
3.) compare order of reponse files

**Comment by GlenDC** [comment]
The URL to your `swagger.json` file doesn't open. Can you please fix it, or upload the json file somewhere it can be seen by the parties interested?

**Comment by claasstoertenbecker** [comment]
Im sorry, the provider of the swagger.json just updated their k8s. 
https://gist.github.com/claasstoertenbecker/88e2d4d0b52e4be8b128bcd199305745
Here you go.

**Comment by GlenDC** [comment]
@claasstoertenbecker once #848 has been merged in (and this issue is closed), the order of your generated code should be consistent in sequential generations. The first time you'll generate with the latest swagger (that contains PR #848), you'll once again have a big diff, potentially bigger than ever. But all generations after that one should not suffer from this issue any longer.

Thanks for reporting this bug!
