### ISSUE TITLE
Documentation for use as a library (--exclude-main)

### ISSUE THREAD

**Issue by OJFord** [go-swagger/go-swagger#888]
I can't see any instructions for how to use the output of `generate server --exclude-main`?

Can that be done in such a way that I can write handlers in some non-generated location (not `restapi/operations`) and attached to the server in my main file? Or do they need to be in the same package, and so must be done by editing the first-run generated files?

**Comment by GlenDC** [comment]
Hello @OJFord first of thank you for using go-swagger, and let me tell you the good news that what you want is indeed already possible. In fact, IMHO it is the most sane approach.

What you could do is keep all your generated code in a single folder, eg `gen` as follows:

- generate client using: `swagger generate client -t gen`
- generate server using: `swagger generate server -t gen --exclude-mean`

After that you can write the cli Application yourself, as well as write the handlers. Swagger will do all the boring work for you, and you can simply concentrate on writing the thin CI (eg flag parsing code, config, ...) and the handler code. Thus you can focus on the stuff you care about, and let swagger take care of all the HTTP code.

For a complete example of this approach you can check out: https://github.com/go-openapi/kvstore/blob/master/doc.go

- it specified the same `gen` target and thus all the generated code can be found here: https://github.com/go-openapi/kvstore/tree/master/gen
- the cli app has been written manually, yet is very small in size, and can be found here: https://github.com/go-openapi/kvstore/blob/master/cmd/kvstored/main.go (handlers assignment L74-77)
  - Note that in this example the producers and consumers are still manually assigned. This is no longer needed as it will by default already assign correct consumers and producers. Be aware that this is till needed in case you want to assign non-supported consumers/producers;
- the handler code is also written manually and can be found here: https://github.com/go-openapi/kvstore/tree/master/api/handlers

Please let me know if this answers your question.

**Comment by OJFord** [comment]
Okay, I think I get it - I was confused by the path (in this case) `gen/restapi/handlers` - but I can just write handlers with the right signature (or set `operationId` in Swagger presumably?) and put them anywhere, as long as they're in `package handlers` - it won't try to look for them on a relative path for example?

**Comment by GlenDC** [comment]
Glad it helps you out, your comment seems to contain 2 questions, so let me first focus on the first one...

Where you put the handlers isn't important, in fact location is never an issue for anything. With Golang it also doesn't matter ever how you name things (except the fact that you can't used some reserved words). With Golang you usually are contracted by an interface or type. Usually you can't choose between the two, but in this case, Go-Swagger provides you the option to implement an interface or a function that adheres to a function type. So let's take kvstore as an example again.

If we check [its swagger yaml specification](https://github.com/go-openapi/kvstore/blob/master/swagger/swagger.yml) (which location or naming is also not important), we can see [there are only 4 operations defined](https://github.com/go-openapi/kvstore/blob/master/swagger/swagger.yml#L53-L207). That means you will have to implement 4 handlers yourself, if you're generating a service using the approach describe above.

[findKeys](https://github.com/go-openapi/kvstore/blob/master/swagger/swagger.yml#L54-L78) is one of them, and is in this project implemented using [the FindKeysHandler interface](https://github.com/go-openapi/kvstore/blob/master/gen/restapi/operations/kv/find_keys.go#L20-L23) in https://github.com/go-openapi/kvstore/blob/master/api/handlers/find_keys.go#L24-L42. This handler is then assigned to the kvstored API here: https://github.com/go-openapi/kvstore/blob/master/cmd/kvstored/main.go#L75, and that's all there is to it.

Now @casualjim choose in this approach to implement each handler, using the interface generated for that handler. But nothing stops you from assigning a standalone function directly. This is possible because there is also a function type generated for every function. For example for [findKeys](https://github.com/go-openapi/kvstore/blob/master/swagger/swagger.yml#L54-L78) this is [the FindKeyHandlerFunc](https://github.com/go-openapi/kvstore/blob/master/gen/restapi/operations/kv/find_keys.go#L12-L13). In case you have a function adhering to that signature, you could assign that function the same way as the interface is assigned.

So with that being said, let's move on to your second question...

The reason the swagger specification is embedded and thus required, is because this is how the Middleware.Context works, which is the core of your generated server. You can see the creation of it here. It used that spec then, in order to know how your API is configured. Because of this it can figure out things like its basePath. That context is also passed along to each route, as can be seen here: https://github.com/go-openapi/kvstore/blob/master/gen/restapi/operations/kvstore_api.go#L233-L251. To know more about this, it might be best for now to simply read through the runtime's middlware package, which can be found here: https://github.com/go-openapi/runtime/tree/master/middleware

Knowledge about how this all works, is however not required in order to use Go-Swagger. What you should remember is that most of the sever is configured dynamically, such that your generated server code can stay as small as possible.

So that's about that. Please let me go how you're getting along with your service, generated by Go-Swagger!

**Comment by GlenDC** [comment]
A tutorial has also be created, that fully explains the techniques and should give you all the info you need in order to create a Golang server using the `--exclude-main` option.

See #889 for more information.
