### ISSUE TITLE
Client Timeout Not Set when Using Structs Directly

### ISSUE THREAD

**Issue by steve-gray** [go-swagger/go-swagger#919]
When using the client code, you need to explicitly set the timeout when allocating the structs for the Params. i.e.

- Call 'NewGetProviderProfileParams'
- Don't call &GetProviderProfileParams{}

The second case doesn't set the default timeout, which now seems to be settable per-request rather than globally for the transport. This is a problem because you instantly get a very bad error message about 'Context deadline exceeded'.

Would suggest:

- If timeout is zero, default to the transport level timeout on the submission of the request.
- Add some more helpful error messaging around the timeout scenario, so you don't get the x/net DeadlineExceeded standard message as an API consumer.

**Comment by casualjim** [comment]
so the point of the constructor method is this exact use case. We need a way to express forever because there are certain cases where you really don't want a request to timeout. 
For example when you write an API that behaves like docker attach/exec.
The reason I let it be context deadline exceeded is exactly because it's a well-known error case that's easy to match for and that matcher is reusable outside the code of go-swagger.

That doesn't mean I would reject a PR from somebody making a more specific error type but I do think it would break a number of applications that already rely on this behavior. So that PR would have to include a flag to opt-in to this behavior at generation time

**Comment by steve-gray** [comment]
Is there any circumstance where the fallback to the default timeout for the client when the request specific one is not set would be undesirable? Happy to leave the errors as is.

**Comment by casualjim** [comment]
The case is for example a long stream over http like server sent events, there you want the connection to be opened forever, forever is signaled by using 0

**Comment by casualjim** [comment]
just to be clear I can't distinguish between unset and 0

**Comment by grillz** [comment]
couldn't the timeout be a pointer? nil becomes the default timeout and you could still set 0 for streams

**Comment by davcamer** [comment]
I'm seeing a 0 timeout behave as "timeout instantly" rather than "wait forever."

**Comment by ToJen** [comment]
I had to use the constructor instead of the struct. I set 120 seconds for the struct approach and that solved it temporarily. The best way to get it working is with the constructor.
