### ISSUE TITLE
More than one tag on a path breaks server code generation

### ISSUE THREAD

**Issue by jbowes** [go-swagger/go-swagger#931]
## Problem statement

A swagger definition that includes more than one tag in a path's tag definitions generates bad code. It appears to nest a second `operations` directory within the first.

## Swagger specification
```yaml
swagger: '2.0'
info:
  title: Multi tag API
  description: multi tag api
  version: '0.0.1'

# the domain of the service
host: api.multi.tags
schemes: [ https ]
produces: [ application/json ]
consumes: [ application/json ]

basePath: /v1 # Prefixed to all paths
paths:
  /multi:
    get:
      summary: A multitag route
      tags:
        - onetag
        - twotag
      responses:
        default:
          description: Unexpected error
          schema:
            type: object
            properties:
              type:
                type: string
                description: The error type
              message:
                type: array
                description: Explanation of the errors
                items: { type: string }
```

## Steps to reproduce
`swagger generate server` with the above, and attempt to go build.

You'll get the following error:
```
restapi/operations/multi_tag_api.go:54: undefined: GetMultiHandler
```

## Environment
swagger version: dev
go version: 1.7.4
OS: macOS

**Comment by aksentyev** [comment]
same issue

**Comment by EleanorRigby** [comment]
Is this still there? 

On my machine with same yaml file as above , it produces perfect output.

Here


```
taggarwal@taggarwal-m01  ~/test-swagger  ./swagger generate server -f bug931.yaml                                                                                                                                                                       ✔  737  17:20:27
2017/08/23 17:44:26 building a plan for generation
2017/08/23 17:44:26 planning definitions
2017/08/23 17:44:26 planning operations
2017/08/23 17:44:26 grouping operations into packages
2017/08/23 17:44:26 planning meta data and facades
2017/08/23 17:44:26 rendering 0 models
2017/08/23 17:44:26 rendering 1 operation groups (tags)
2017/08/23 17:44:26 rendering 1 operations for operations
2017/08/23 17:44:26 rendering 4 templates for operation
2017/08/23 17:44:26 name field GetMulti
2017/08/23 17:44:26 package field operations
2017/08/23 17:44:26 creating "get_multi_parameters.go" in "restapi/operations/operations" as parameters
2017/08/23 17:44:26 name field GetMulti
2017/08/23 17:44:26 package field operations
2017/08/23 17:44:26 creating "get_multi_urlbuilder.go" in "restapi/operations/operations" as urlbuilder
2017/08/23 17:44:26 name field GetMulti
2017/08/23 17:44:26 package field operations
2017/08/23 17:44:26 creating "get_multi_responses.go" in "restapi/operations/operations" as responses
2017/08/23 17:44:26 name field GetMulti
2017/08/23 17:44:26 package field operations
2017/08/23 17:44:26 creating "get_multi.go" in "restapi/operations/operations" as handler
2017/08/23 17:44:27 rendering support
2017/08/23 17:44:27 rendering 6 templates for application MultiTag
2017/08/23 17:44:27 name field MultiTag
2017/08/23 17:44:27 package field operations
2017/08/23 17:44:27 creating "configure_multi_tag.go" in "restapi" as configure
2017/08/23 17:44:27 name field MultiTag
2017/08/23 17:44:27 package field operations
2017/08/23 17:44:27 creating "main.go" in "cmd/multi-tag-server" as main
2017/08/23 17:44:27 name field MultiTag
2017/08/23 17:44:27 package field operations
2017/08/23 17:44:27 creating "embedded_spec.go" in "restapi" as embedded_spec
2017/08/23 17:44:27 name field MultiTag
2017/08/23 17:44:27 package field operations
2017/08/23 17:44:27 creating "server.go" in "restapi" as server
2017/08/23 17:44:27 name field MultiTag
2017/08/23 17:44:27 package field operations
2017/08/23 17:44:27 creating "multi_tag_api.go" in "restapi/operations" as builder
2017/08/23 17:44:27 name field MultiTag
2017/08/23 17:44:27 package field operations
2017/08/23 17:44:27 creating "doc.go" in "restapi" as doc
Generation completed!

For this generation to compile you need to have some packages in your GOPATH:

  * github.com/go-openapi/runtime
  * github.com/tylerb/graceful
  * github.com/jessevdk/go-flags

You can get these now with: go get -u -f ./...

taggarwal@taggarwal-m01  ~/test-swagger  ls -R                                                                                                                                                                                                          ✔  741  17:45:19
bug931.yaml    cmd            copyright.txt  copyright.txt~ pet.yaml       restapi        swagger

./cmd:
app-server       multi-tag-server

./cmd/app-server:
main.go

./cmd/multi-tag-server:
main.go

./restapi:
configure_app.go       configure_multi_tag.go doc.go                 embedded_spec.go       operations             server.go

./restapi/operations:
app_api.go       multi_tag_api.go operations

./restapi/operations/operations:
get_multi.go            get_multi_parameters.go get_multi_responses.go  get_multi_urlbuilder.go
 taggarwal@taggarwal-m01  ~/test-swagger 
```

**Comment by EleanorRigby** [comment]
@casualjim : It has been verified. Can be closed.

**Comment by casualjim** [comment]
there shouldn't be a nested operations/operations folder

**Comment by jgsprasad** [comment]
Im seeing the operations/operations folder created. Tried to compile my generated server but getting compile errors. 
2017/09/05 14:22:18 building a plan for generation
2017/09/05 14:22:18 planning definitions
2017/09/05 14:22:18 planning operations
2017/09/05 14:22:18 grouping operations into packages
2017/09/05 14:22:18 planning meta data and facades
2017/09/05 14:22:18 rendering 3 models
2017/09/05 14:22:18 rendering 1 templates for model uuid
2017/09/05 14:22:18 name field uuid
2017/09/05 14:22:18 package field models
2017/09/05 14:22:18 creating "uuid.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/models" as definition
2017/09/05 14:22:18 rendering 1 templates for model error
2017/09/05 14:22:18 name field error
2017/09/05 14:22:18 package field models
2017/09/05 14:22:18 creating "error.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/models" as definition
2017/09/05 14:22:18 rendering 1 templates for model success
2017/09/05 14:22:18 name field success
2017/09/05 14:22:18 package field models
2017/09/05 14:22:18 creating "success.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/models" as definition
2017/09/05 14:22:18 rendering 1 operation groups (tags)
2017/09/05 14:22:18 rendering 1 operations for operations
2017/09/05 14:22:18 rendering 4 templates for operation nusights-rest-api
2017/09/05 14:22:18 name field fileupload
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "fileupload_parameters.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi/operations/operations" as parameters
2017/09/05 14:22:18 name field fileupload
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "fileupload_urlbuilder.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi/operations/operations" as urlbuilder
2017/09/05 14:22:18 name field fileupload
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "fileupload_responses.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi/operations/operations" as responses
2017/09/05 14:22:18 name field fileupload
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "fileupload.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi/operations/operations" as handler
2017/09/05 14:22:18 rendering support
2017/09/05 14:22:18 rendering 6 templates for application NusightsRest
2017/09/05 14:22:18 name field NusightsRest
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 skipping /home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi/configure_nusights_rest.go because it already exists
2017/09/05 14:22:18 name field NusightsRest
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "main.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/cmd/nusights-rest-server" as main
2017/09/05 14:22:18 name field NusightsRest
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "embedded_spec.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi" as embedded_spec
2017/09/05 14:22:18 name field NusightsRest
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "server.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi" as server
2017/09/05 14:22:18 name field NusightsRest
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "nusights_rest_api.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi/operations" as builder
2017/09/05 14:22:18 name field NusightsRest
2017/09/05 14:22:18 package field operations
2017/09/05 14:22:18 creating "doc.go" in "/home/prasadj/workspace/main6/.go/src/nusights/server/apis/restapi" as doc
Generation completed!
Invoking go build for nusights_server_apis_cmd_nusights-rest-server
# nusights/server/apis/restapi/operations
.go/src/nusights/server/apis/restapi/operations/nusights_rest_api.go:71: undefined: FileuploadHandler
make[3]: *** [nusights/go/nusights/server/apis/cmd/nusights-rest-server/CMakeFiles/nusights_server_apis_cmd_nusights-rest-server] Error 2

**Comment by EleanorRigby** [comment]
@jgsprasad : Can you try with latest pull from https://github.com/EleanorRigby/go-swagger
