### ISSUE TITLE
Architecture question: how to avoid deep copies of complex data structures that need to be marshalled across the API?

### ISSUE THREAD

**Issue by Ravenwater** [go-swagger/go-swagger#948]
## Problem statement
An API that provides access to a complex data structure that is defined and governed by a subsystem should not have to spec the same data model to be marshalled, as this would require a deep copy of the data structure from the subsystem to the API layer's model universe.

How do others deal with this problem?

In more detail: a subsystem that builds a complex hierarchical data structure to support its own requirements for efficiency, access, and serialization does not want the types of the API data model to be injected into its namespace. Furthermore, the subsystem can exist in many different contexts beyond the API, which is another reason it would not want to become dependent on any API types.

A new requirement is proposed that wants API access to that complex data structure, and we decide to use go-swagger for that implementation. It is a pure 'read' requirement, so no need for parameter validation by the API, just the ability to gain an XML or JSON form of the data structure by a client. If we define a data model in the swagger specification we end up having to do a deep copy of that data structure from subsystem to API if we want to avoid type injection.

How do you use the swagger spec to define a raw JSON or XML transfer, defined by the subsystem's types?

**Comment by dhoelle** [comment]
@Ravenwater we have the same issue. Our organization decided to keep the API and subsystem layers separate, and to perform deep copies between them. The runtime performance costs are acceptable to us, and worth it to keep API-layer dependencies out of our core library. If someone can think of a better solution we would love to know!

W.R.T. your second question, I'm not sure I fully understand it.

If your question is "How do I write arbitrary response bodies from `go-swagger` generated server code?" (e.g. from subsystem structs that you have marshaled) then you may want to write your own [middleware.Responder](https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L56-L60), which gives you direct access to the underlying `http.ResponseWriter`. (At this point, though, I wonder: why use go-swagger instead of a lighter-weight framework?)

If your question is "how can I generate a swagger spec from my subsystem structs?", then you should check out the `swagger generate spec` CLI command.

If I've missed the meaning of your question, my apologies, and if you can provide a more concrete example of your use case I'll try to help more!

**Comment by casualjim** [comment]
and we also have an extension that allows you to use pre-existing types as models, you annotate your spec like this:
https://github.com/go-swagger/go-swagger/blob/master/fixtures/codegen/existing-model.yml#L84-L88
