### ISSUE TITLE
How to write comment when API accepts json body?

### ISSUE THREAD

**Issue by Krashcan** [go-swagger/go-swagger#970]
## Problem statement
My web app accepts json body instead of individual parameters, so I want to be able to submit a single json body. From the documentation it is not clear how to write comments for this purpose. I don't know how I should use swagger:model or swagger:parameter here. Can you provide me a sample commented code for this example please:-

    type test struct{
        test1 string `json:"test1"`
        test2 string `json:"test2"`
    }

**Comment by casualjim** [comment]
```
type testresponse struct {
  // in: body
  Body test
}
```

**Comment by stefanhendriks** [comment]
I know this is a very old issue - but I do wonder how this would work with a linter that removes `deadcode`. Defining a struct just so that you can define a `body` for swagger will result into a working swagger doc *but* the linter will not like it. Of course we can mark this with `//nolint`. 

Would'nt it be nice if we could put `in: body` above the `type test struct {` part?

**Comment by casualjim** [comment]
You can use `body:test` in the swagger route 

https://github.com/go-swagger/go-swagger/blob/43c2774170504d87b104e3e4d68626aac2cd447d/fixtures/goparsing/classification/operations_body/todo_operation_body.go#L47-L50
